languages:
  JavaScript: true
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
    checks:
      Similar code:
        enabled: false
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_paths:
- "build/*"
- "test/**"
- "examples/**"
