engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    languages:
      - JavaScript
    checks:
      Similar code:
        enabled: false
exclude_paths:
- "build/*"
- "test/**"
- "examples/**"
